name: third workflow
on: 
  schedule:
    - cron: '* * 1 * *'
  push:
    branches:
      - main
  workflow_dispatch:    
jobs:
  test_1: 
    runs-on: ubuntu-latest
    steps:
      - run : echo thanks
        name: thanks
